language: node_js
sudo: required
node_js:
  - "6"
before_script:
  - "npm install -g typescript && npm install && tsc"
cache:
  directories:
    - "node_modules"
deploy:
  provider: npm
  email: inf3cti0n95@gmail.com
  api_key:
    secure: 7DGcpItadJpvJ7fKc7xr00kXi1H3i9+9SJ1X5X3dPaUvH3UvyiSdMpf0L8PTvEha782l1Rm8K6immz5w7+DBdnGFG3DBBGqOGKRFyQGFHgw4N8HyfPZVEXeNMidkBIAnP/tsBrNht1LW6Qecihwzdk4Ech1fEw5Cf0VpHybAyWyxG+7rDwPV8wY93mRUjyDgToSWXmFICadD7Bq0cMOxYaQHcINJvPsDjOTrQ1y3nkj+nVzCO3Oyx7LKrtZ5b6aXdFtYBi2fkLFN8D/hVn+sCQiV8rHBQU7v+x4FRwDKJHShPusbH0TVnkMGbuE4+/zf+ZCrqAQ5fYcZ0AIMpqngUnIajBvQYPxqaAJ6HgFHVAbN4Z54QXr8ebQcBBF5cEK6AQIWiKlOIsLc3e4ximudTfZEShFdnECWJtE3wdlRFz9ppwSxWxNowrgji+I1ThyBCrj0AGG8bJSSVCXxOGTHUKwE610D9jg44cJN/AxmGE5L8r7J4NmFWfSutvjTI/dYsjlcB+F+CSfpUC8u13H818LIYF2mVIpBV5rbhZSw9NYWury0jVkaW2D4builNp0r/AWiKxu9S5dLL4QU3SuKn/Vu7wxDlPvxgJqXfgccxCLtDc8oK6odCYKKsOew7EeLTQPhvTFRIxs7slivK0DCLWe/LI9sUqPzYD03ir8SVgo=
  on:
    repo: inf3cti0n95/Rocket.Chat.RealTime.API.RxJS
